
/*
 * main_v2.c  (STM32C0xx-ready)
 *
 * Reads time from DS3231 over I2C and displays HH:MM on TA6932 over SPI.
 * - Target MCU: STM32C0xx (HAL)
 * - SPI ~750 kHz (<=1 MHz), Mode 0
 */

#include "stm32c0xx_hal.h"
#include "main.h"
#include "ds3231_v2.h"

/* Externs generated by CubeMX for STM32C0xx */
extern I2C_HandleTypeDef hi2c1;
extern SPI_HandleTypeDef hspi1;

/* TA6932 STB pin — EDIT to your actual pin mapping */
#define TA6932_STB_GPIO_Port    GPIOA
#define TA6932_STB_Pin          GPIO_PIN_4

static inline void TA6932_STB_H(void){ HAL_GPIO_WritePin(TA6932_STB_GPIO_Port, TA6932_STB_Pin, GPIO_PIN_SET); }
static inline void TA6932_STB_L(void){ HAL_GPIO_WritePin(TA6932_STB_GPIO_Port, TA6932_STB_Pin, GPIO_PIN_RESET); }

static void TA6932_SendByte(uint8_t b){ HAL_SPI_Transmit(&hspi1, &b, 1, 1000); }

static void TA6932_SendCommand(uint8_t cmd){
    TA6932_STB_L();
    TA6932_SendByte(cmd);
    TA6932_STB_H();
}

static void TA6932_WriteDataSeq(uint8_t startAddr, const uint8_t *p, uint8_t n){
    if (!n) return;
    TA6932_SendCommand(0x40);                 // data write, auto-inc
    TA6932_STB_L();
    TA6932_SendByte(0xC0 | (startAddr & 0x0F));
    for (uint8_t i=0;i<n;i++) TA6932_SendByte(p[i]);
    TA6932_STB_H();
}

static void TA6932_DisplayOn(uint8_t level){
    if (level>7) level=7;
    TA6932_SendCommand(0x88 | level);
}

static const uint8_t segFont[10] = {
    0x3F,0x06,0x5B,0x4F,0x66,0x6D,0x7D,0x07,0x7F,0x6F
};

static uint8_t makeDigit(uint8_t d, uint8_t dp){
    uint8_t v = segFont[d%10];
    if (dp) v |= 0x80; // dp
    return v;
}

static void TA6932_ShowTimeHHMM(uint8_t h, uint8_t m, uint8_t showColon){
    uint8_t b[4];
    b[0] = makeDigit(h/10, 0);
    b[1] = makeDigit(h%10, showColon);
    b[2] = makeDigit(m/10, 0);
    b[3] = makeDigit(m%10, 0);
    TA6932_WriteDataSeq(0x00, b, 4);
}

/* Prototypes generated by CubeMX */
void SystemClock_Config(void);
void MX_GPIO_Init(void);
void MX_I2C1_Init(void);
void MX_SPI1_Init(void);

int main(void){
    HAL_Init();
    SystemClock_Config();
    MX_GPIO_Init();
    MX_I2C1_Init();
    MX_SPI1_Init();

    HAL_GPIO_WritePin(TA6932_STB_GPIO_Port, TA6932_STB_Pin, GPIO_PIN_SET);

    DS3231_Init(&hi2c1);
    (void)DS3231_Enable1HzSQW();

    TA6932_DisplayOn(6);

    DS3231_TimeTypeDef t;
    uint8_t prevSec = 255, blink = 0;

    while (1){
        if (DS3231_GetTime(&t) == HAL_OK){
            if (t.seconds != prevSec){
                prevSec = t.seconds;
                blink ^= 1;
                TA6932_ShowTimeHHMM(t.hours, t.minutes, blink);
            }
        }
        HAL_Delay(50);
    }
}
